---
title: "hw1_ans"
author: "Euijong Song"
date: "2025-10-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## 총점: 65점
##  문제 0 (5점)
```{r}
##주석을 이용해 아무말이라도 작성한경우 점수 주기.
```


### 문제 1.1 (10점)
```{r}
six <- seq(from = 6, to = 500, by = 6)
total <- sum(six)
```

### 문제 1.2 (10점)
```{r}
m <- mean(six)
s <- sqrt(var(six) * (length(six)-1) / length(six))
```

### 문제 2.1 (10점)
```{r}
X <- matrix(1:36, ncol = 6, byrow = TRUE)
```

### 문제 2.2 (10점)
```{r}
Y <- X %% 4
```

## 문제 3 - DataFrame (20점)
```{r}
data("iris")
setosa <- as.data.frame(iris[1:50, 1:4])
```

### 문제 3.1 (5점)
```{r}
Sepal <-setosa[,1] + setosa[,2]
```

### 문제 3.2 (5점)

```{r}
summary(Sepal)
```


### 문제 3.3 (5점)
```{r}
plot(setosa[,3], setosa[,4], 
     main = "Correlation of Petal Length and Petal Width",  # 제목 설정
     xlab = "Length",  # x축 이름
     ylab = "Width",   # y축 이름
     xlim = c(0.5, 2),   # x축 범위 설정
     ylim = c(0, 1))   
```



### 문제 3.4 (5점)
```{r}
result <- cor(setosa[,3], setosa[,4])
```




